/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnisample_Main */

#ifndef _Included_com_jnisample_Main
#define _Included_com_jnisample_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnisample_Main
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnisample_Main_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
